"""Train RealNVP on MNIST by exact maximum likelihood; report bits/dim and samples.

Run:
    python -m a2_normalizing_flows.train --epochs 8 --results results/a2_flow

Produces:
    results/a2_flow/samples.png   -- images generated by z ~ N(0,I) -> inverse flow
    results/a2_flow/metrics.json  -- test bits/dim (lower = better)
"""
from __future__ import annotations

import argparse
import json
import math
import os
import time

import torch

from common.data import get_mnist_loaders
from common.utils import configure_cpu, count_params, save_image_grid, set_seed
from a2_normalizing_flows.model import RealNVP, inverse_logit, logit_transform


def bits_per_dim(log_prob: torch.Tensor, ldj: torch.Tensor, dim: int) -> torch.Tensor:
    """Convert total log-likelihood (nats) to bits/dim.

    log p(x_pixels) = model.log_prob(y) + ldj_of_preprocessing.
    bits/dim = -log p / (dim * log 2).
    """
    total = log_prob + ldj
    return -(total / (dim * math.log(2)))


def evaluate(model: RealNVP, loader, device) -> float:
    model.eval()
    total, n = 0.0, 0
    with torch.no_grad():
        for x, _ in loader:
            x = x.view(x.size(0), -1).to(device)
            y, ldj = logit_transform(x)
            lp = model.log_prob(y)
            bpd = bits_per_dim(lp, ldj, model.dim)
            total += bpd.sum().item()
            n += x.size(0)
    return total / n


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--epochs", type=int, default=8)
    p.add_argument("--batch-size", type=int, default=128)
    p.add_argument("--lr", type=float, default=1e-4)
    p.add_argument("--n-coupling", type=int, default=6)
    p.add_argument("--hidden", type=int, default=256)
    p.add_argument("--train-subset", type=int, default=None)
    p.add_argument("--results", type=str, default="results/a2_flow")
    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args()

    set_seed(args.seed)
    configure_cpu()
    device = torch.device("cpu")
    os.makedirs(args.results, exist_ok=True)

    train_loader, test_loader = get_mnist_loaders(
        batch_size=args.batch_size, train_subset=args.train_subset
    )
    model = RealNVP(dim=784, n_coupling=args.n_coupling, hidden=args.hidden).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=args.lr)
    print(f"RealNVP params: {count_params(model):,}")

    history = []
    t0 = time.time()
    for epoch in range(1, args.epochs + 1):
        model.train()
        run, nb = 0.0, 0
        for x, _ in train_loader:
            x = x.view(x.size(0), -1).to(device)
            y, ldj = logit_transform(x)
            lp = model.log_prob(y)
            bpd = bits_per_dim(lp, ldj, model.dim).mean()
            opt.zero_grad()
            bpd.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            opt.step()
            run += bpd.item()
            nb += 1
        train_bpd = run / nb
        test_bpd = evaluate(model, test_loader, device)
        history.append({"epoch": epoch, "train_bpd": train_bpd, "test_bpd": test_bpd})
        print(f"epoch {epoch:2d}  train bpd {train_bpd:.4f}  test bpd {test_bpd:.4f}")

    train_time = time.time() - t0

    samples = model.sample(64, device=device)
    imgs = inverse_logit(samples).view(-1, 1, 28, 28)
    save_image_grid(imgs, os.path.join(args.results, "samples.png"), nrow=8)

    metrics = {
        "model": "RealNVP (Dinh et al. 2017)",
        "params": count_params(model),
        "epochs": args.epochs,
        "n_coupling": args.n_coupling,
        "final_test_bits_per_dim": history[-1]["test_bpd"],
        "train_seconds": round(train_time, 1),
        "history": history,
    }
    with open(os.path.join(args.results, "metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"\nTest bits/dim: {metrics['final_test_bits_per_dim']:.4f}")
    print(f"Saved samples + metrics to {args.results}")


if __name__ == "__main__":
    main()
